version: 2

jobs:
  build-library-service-jdk8:
    working_directory: ~/build-library-service-jdk8
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run: cd library-service && ./gradlew unitTest
      - store_test_results:
          path: library-service/build/test-results/unitTest
          destination: unit-tests
      - run: cd library-service && ./gradlew integrationTest
      - store_test_results:
          path: library-service/build/test-results/integrationTest
          destination: integration-tests
      - run: cd library-service && ./gradlew acceptanceTest
      - store_test_results:
          path: library-service/build/test-results/acceptanceTest
          destination: acceptance-tests
      - run: cd library-service && ./gradlew contractTest
      - store_test_results:
          path: library-service/build/test-results/contractTest
          destination: contract-tests

  build-library-service-jdk11:
    working_directory: ~/build-library-service-jdk8
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run: cd library-service && ./gradlew unitTest
      - store_test_results:
          path: library-service/build/test-results/unitTest
          destination: unit-tests
      - run: cd library-service && ./gradlew integrationTest
      - store_test_results:
          path: library-service/build/test-results/integrationTest
          destination: integration-tests
      - run: cd library-service && ./gradlew acceptanceTest
      - store_test_results:
          path: library-service/build/test-results/acceptanceTest
          destination: acceptance-tests
      - run: cd library-service && ./gradlew contractTest
      - store_test_results:
          path: library-service/build/test-results/contractTest
          destination: contract-tests

workflows:
  version: 2
  build-library-service:
    jobs:
    - build-library-service-jdk8
    - build-library-service-jdk11
